packageExtensions:
  # Gatsby is missing this dependency, which causes TS resolution to fail
  gatsby@*:
    dependencies:
      "@types/reach__router": ^1.3.10
  # Missing dep for typing
  "@chakra-ui/styled-system@*":
    dependencies:
      "@chakra-ui/breakpoint-utils": "*"

# Other dependency notes:
# @chakra-ui/theme patch - https://github.com/chakra-ui/chakra-ui/issues/7116#issuecomment-1408840666

plugins:
  - path: .yarn/plugins/@yarnpkg/plugin-interactive-tools.cjs
    spec: "@yarnpkg/plugin-interactive-tools"
  - path: .yarn/plugins/@yarnpkg/plugin-typescript.cjs
    spec: "@yarnpkg/plugin-typescript"

yarnPath: .yarn/releases/yarn-3.4.1.cjs
