# FIXME: https://github.com/chakra-ui/chakra-ui/issues/6756
packageExtensions:
  "@chakra-ui/react@^2.3.4 >=2.2.5":
    dependencies:
      "@chakra-ui/styled-system": ^2.3.3
  "@chakra-ui/toast@^3.0.12":
    dependencies:
      "@chakra-ui/styled-system": ^2.3.3

plugins:
  - path: .yarn/plugins/@yarnpkg/plugin-interactive-tools.cjs
    spec: "@yarnpkg/plugin-interactive-tools"
  - path: .yarn/plugins/@yarnpkg/plugin-typescript.cjs
    spec: "@yarnpkg/plugin-typescript"

yarnPath: .yarn/releases/yarn-3.2.3.cjs
